#!/bin/bash

# zk_user also defined in /etc/init.d/zookeeper and needs to match this value
ZK_USER=tomcat7
ZK_ROOT=/var/lib/zookeeper

# grant jetty directories to jetty user
chown ${ZK_USER}:${ZK_USER} -R ${ZK_ROOT}

chmod +x /etc/init.d/zookeeper

exit 0
